### ISSUE TITLE
How can I update the graph definition of PIxela?

### ISSUE THREAD

**Issue by ebc-2in2crc** [yutailang0119/PixelaUI-App#1]
Hi.

PixelaUI is so cool!
I use PixelaUI every day, but I'm having a little trouble.
I don't know how to use PixelaUI to update the graph definition in Pixela.
How can I update the graph definition of PIxela?

- iOS: 14.4
- PixelaUI: 0.6.0

Thanks!

**Comment by yutailang0119** [comment]
Hi,

Thanks for using PixelaUI!

Currently, PixelaUI doesn't support to update graph define.
Please update in other ways.

Thanks.

**Comment by ebc-2in2crc** [comment]
Thanks for the reply.

I understand, I will be going to update the graph definition in other ways.

Thanks!
